// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATVrFPcNB-w6xwLCm6OhcaZZpvjJBLFcg',
    appId: '1:385876884775:web:8a23d7bfc8d3435b457d02',
    messagingSenderId: '385876884775',
    projectId: 'social-media-app-b8447',
    authDomain: 'social-media-app-b8447.firebaseapp.com',
    storageBucket: 'social-media-app-b8447.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEyp8-JG97xnueDlpyr-F19LKldiyVfWs',
    appId: '1:385876884775:android:774ec03c266d52bf457d02',
    messagingSenderId: '385876884775',
    projectId: 'social-media-app-b8447',
    storageBucket: 'social-media-app-b8447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-nmsJ2CyqGl9OlErsN-fVUdzlLfd8weo',
    appId: '1:385876884775:ios:e0be07d1d89f895d457d02',
    messagingSenderId: '385876884775',
    projectId: 'social-media-app-b8447',
    storageBucket: 'social-media-app-b8447.appspot.com',
    iosClientId: '385876884775-h1o61hijc37o76icc03uls0tt1t1vigi.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-nmsJ2CyqGl9OlErsN-fVUdzlLfd8weo',
    appId: '1:385876884775:ios:c0f369b01e68dfc8457d02',
    messagingSenderId: '385876884775',
    projectId: 'social-media-app-b8447',
    storageBucket: 'social-media-app-b8447.appspot.com',
    iosClientId: '385876884775-q1fvfjo10vaevil945hac4vjrp74hit5.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
